### ISSUE TITLE
Whitelisting buttons instead of blacklisting

### ISSUE THREAD

**Issue by erksch** [paypal/paypal-checkout-components#1033]
Hey there!

I integrated with the new SDK in my React project and beside the trouble of including a script that are described here #1028. I'm also having trouble to use the buttons separately. 

It seems like the buttons are designed to be used all at once and you can disable some of them with the disable-funding config. But I want to use the buttons separately and manage my the payment method selection on own. There are two major blockers for this:
1. I can not disable the paypal button, so there is no chance for me to display for example the SEPA button standalone.
2. I am not sure if I can create a standalone paypal button either because I can only disable `card, credit and sepa`. Will the google pay, apple pay or deferred payment buttons still show up even if I **only** want the paypal button?

I guess it's nice that payment methods are added automatically to the buttons if there are supported but I would wish some more options here because not every site works the same or is okay with using all buttons at once. To help people with configuration issues like me, you could either expand the `disable-funding` functionality for all the payment methods or do something like a whitelist or `enable-funding`.

Also, as described in #1028 configurating the script in multiple ways can be pretty annoying since I have to reload the entire script just to show another specific button. Why don't you defer the disabling button configuration in the `paypal.Buttons(config)` like all the layouting etc.? 
In my opinion, configuring stuff over a script tag does not seem very suitable for the modern javascript world.

**Comment by erksch** [comment]
Also another thing: This repo obviously seems to be for the deprecated `checkout.js` API and you already talked about deprecating it. Is there any other place where issues like this one can be opened to really address the new Smart Payment Buttons? Do you plan to release an npm package for that too? Or am I missing an already existing github repo?

**Comment by erksch** [comment]
Okay I actually just found your repo "paypal-smart-payment-buttons" sorry for that. 
If you want I can open a new issue there.

**Comment by bluepnume** [comment]
Hi. This is the right repo for questions like this 👍 

Can I understand your use-case a little more? The SPB is designed to show the best possible range of buttons for a buyer visiting your site. What you see may not be the same as any of your customers.

Can I understand the concern with the buttons that are currently being shown? Is this more of a UI concern, or something else?

The reason these are configured at the script tag level is, it actually enables the script we serve up to your site to be way more lightweight; since we only load the resources that are specifically needed in any given scenario. Can you elaborate on the use-case where you need to reload the script?
