### ISSUE TITLE
Checkout popup fires onCancel immediately after loading

### ISSUE THREAD

**Issue by sandymca94** [paypal/paypal-checkout-components#1087]
Hi, 

I am also getting the same issue - "Checkout popup fires onCancel immediately after loading" on Edge.

For temporary solution I did this as suggested in this article - "https://github.com/paypal/paypal-checkout-components/issues/959" but I can't give this solution to our client.

 I added the internal server and the "https://www.sandbox.paypal.com" size to the trusted Sites and restarted the Browser then its working fine.

Can some one please suggest me a proper solution for "Edge" browser.

<script>
  
    paypal.Button.render({
        //env: 'sandbox', // sandbox | production
        env: '@Model.ConfigData.PayPalMode.ToLower()',
        // PayPal Client IDs - replace with your own
        // Create a PayPal app: https://developer.paypal.com/developer/applications/create
        //if('@Model.ConfigData.PayPalMode.ToLower()' = 'sandbox')
        client: {
            //sandbox: 'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R',
            sandbox: '@Model.ConfigData.PaypalClientId'
        },
        // Specify the style of the button
        style: {
            //layout: 'vertical',  // horizontal | vertical
            size: 'responsive',    // medium | large | responsive
            shape: 'rect',      // pill | rect
            color: 'blue'       // gold | blue | silver | white | black
        },

        // Show the buyer a 'Pay Now' button in the checkout flow
        commit: true,

        // payment() is called when the button is clicked
        payment: function (data, actions) {
            
            // Make a call to the REST api to create the payment
            return actions.payment.create({
                payment: {
                    transactions: [
                        {
                            @{
                                string strCurrencyValue = string.Empty;
                                if (@Model.ConfigData.AutoFill.ToString().ToLower() == "yes") {
                                    strCurrencyValue = @Model.ConfigData.BaseCurrency;
                                }
                                else {
                                     strCurrencyValue = @Model.ConfigData.CurrencySign;
                                }
                            }
                            amount: { total: '@Model.CreditData.PaymentAmount', currency: '@strCurrencyValue' },
                            //invoice_number: '@Model.CreditData.TransactionID',
                            description: 'Your payment reference number is :' + '@Model.CreditData.TransactionID.ToString()',
                            reference_id: '@Model.InvoiceData.InvoiceReference'
                        }
                    ],
                    redirect_urls: {
                        @{
                            string returnValue = string.Empty;
                            if (@Model.ConfigData.Encoding.ToString().ToLower() == "true" && (!string.IsNullOrEmpty(@Model.InvoiceData.rawURL)))
                            {
                                byte[] toEncodeAsBytes = System.Text.Encoding.UTF8.GetBytes(@Model.InvoiceData.rawURL);
                                returnValue = System.Convert.ToBase64String(toEncodeAsBytes);
                            }
                            else
                            {
                                returnValue = @Model.InvoiceData.rawURL;
                            }
                        }
                        return_url: window.location.protocol.replace(":", "") + "://" + window.location.host.replace("/", "") + '/' + window.location.pathname.replace("/", "") + '?Success=True&RawURL=' + '@returnValue',
                        cancel_url: window.location.protocol.replace(":", "") + "://" + window.location.host.replace("/", "") + '/' + window.location.pathname.replace("/", "") + '?Success=False'
                    }
                }
            });
        },

        // onAuthorize() is called when the buyer approves the payment
        onAuthorize: function (data, actions) {
            
            jQuery.event.trigger("ajaxStart");
            //$("#btnNext").attr('disabled', 'disabled');
            var return_url = '';
            // Make a call to the REST api to execute the payment
            actions.payment.execute().then(function () {
                //console.log(data);
                return_url = data.returnUrl;
            });

            actions.payment.execute().then(function (res) {
                               
                if (res.state === 'approved') {
                    //console.log(res);                
                    console.log(res);

                } else {
                    console.log(res);
                                     
                }
            }).catch(function (error) {
                console.log(error);
            });
        },
        // Pass a function to be called when the customer cancels the payment
        onCancel: function (data, actions) {
            console.log(data);
        },
        onError: function (error) {
            console.log(error);
        }

    }, '#paypal-button-container');

</script>

Thanks
Sandeep

_Originally posted by @sandymca94 in https://github.com/paypal/paypal-checkout-components/issues/750#issuecomment-486108933_

**Comment by fra105** [comment]
Since i am working on the same issue right now i will post this here and not open a new one:

----

### Description

After the button is clicked and the popup finished loading, onCancel is called immediately and finally onError is called and the overlay disappears but the popup stays open.

I found similiar Issues here already closed, telling us to change our internet/intranet settings and trusted sites. This may work for IE but not for Edge and we can also not tell customers to change settings on their browser before placing an order with us...

Code used (same as https://developer.paypal.com/demo/checkout, only added onCancel and onError):
<!DOCTYPE html>
<html>
    <head>
        
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    </head>

    <body>
        <div id="paypal-button-container"></div>

        <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>

        <script>
            paypal.Buttons({

                // Set up the transaction
                createOrder: function(data, actions) {
                    return actions.order.create({
                        purchase_units: [{
                            amount: {
                                value: '0.01'
                            }
                        }]
                    });
                },

                // Finalize the transaction
                onApprove: function(data, actions) {
                    return actions.order.capture().then(function(details) {
                        // Show a success message to the buyer
                        alert('Transaction completed by ' + details.payer.name.given_name + '!');
                    });
                },

                onCancel: function(data) {
                    console.log('onCancel');
                    console.log(data);
                },

                onError: function(err) {
                    console.log('onError');
                    console.log(err);
                }

            }).render('#paypal-button-container');
        </script>
    </body>
</html>

This is what is passed to onError:

`{code: undefined, description: "The remote server machine does not exist or is unavailable", message: "The remote server machine does not exist or is unavailable", stack: "Error: The remote server machine does not exist or is unavailable at e.has (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:14650) at e.getOrSet (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:14773) at r (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:49734) at get (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:49830) at Ar (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:68001) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:75617) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:16551) at all (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:19309) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:89070) at i (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:5392) Error: The remote server machine does not exist or is unavailable at $t[] (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:51946) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:58198) at JSON.parse (native code) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:58055) at lr (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:57995) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:62979) at vr (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:62933) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:67607) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:67384)"}`

Some times the same error occurs but message and description fields are empty:

`{code: undefined, description: "", message: "", stack: "Error at e.has (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:14650) at e.getOrSet (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:14773) at r (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:49734) at get (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:49830) at Ar (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:68001) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:75617) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:16551) at all (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:19309) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:89070) at i (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:5392) Error at $t[] (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:51946) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:58198) at JSON.parse (native code) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:58055) at lr (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:57995) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:62979) at vr (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:62933) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:67607) at Anonymous function (https://www.paypal.com/sdk/js?client-id=sb&currency=USD:1:67384)"}`

- paypal version 5.0.24
- browser version 42.17134.1.0
- On https://developer.paypal.com/demo/checkout The Error does NOT occur automatically. The Error only occurs after the popup is closed manually pressing X. onCancel is called correctly then but also onError is called with the same error as above
- the issue orccurs consistently

Output after a single click on the first button:
![pp-issue](https://user-images.githubusercontent.com/49941587/56655216-707cdb80-6692-11e9-9251-1f0a31b7c933.png)

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by fra105** [comment]
Now after i cleared my cache and cookies and everything on my Edge, i can not reproduce this issue anymore. At least onCancel is not called automatically. But onError is still called after the popup is closed manually by pressing X with the message "The remote server machine does not exist or is unavailable".

But clearing browser data is not a solution. The initial issue will still occur to some customers that are using Edge and have not cleared their browser data yet. Luckily there are only few of them

**Comment by sandymca94** [comment]
No it didn't help me, as I cleaned my cache and cookies and everything on my Edge but still it is not working and getting the same issue.

Description

After the button is clicked and the popup finished loading, onCancel is called immediately and overlay disappears but the popup stays open.

I found some link in GitHub - https://github.com/paypal/paypal-checkout-components/issues/750 and already closed, telling us to change our internet/intranet settings and trusted sites. This may work for IE but not for Edge and we can also not tell customers to change settings on their browser before placing an order with us.

Code used (same as https://developer.paypal.com/docs/archive/checkout/how-to/customize-flow/#, only added onCancel and onError):

 

<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<script type="text/javascript" src="https://www.paypalobjects.com/api/checkout.js"></script>

 

paypal.Button.render({
//env: 'sandbox', // sandbox | production
env: 'sandbox',
client: {
//sandbox: 'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R',
sandbox: '@Model.ConfigData.PaypalClientId',
production: 'xxxxxx'
},
// Specify the style of the button
style: {
//layout: 'vertical', // horizontal | vertical
size: 'responsive', // medium | large | responsive
shape: 'rect', // pill | rect
color: 'blue' // gold | blue | silver | white | black
},

// Show the buyer a 'Pay Now' button in the checkout flow
commit: true,

// payment() is called when the button is clicked
payment: function (data, actions) {
debugger;
// Make a call to the REST api to create the payment
return actions.payment.create({
payment: {
transactions: [
{
amount: { total: '@Model.CreditData.PaymentAmount', currency: 'USD' },
//invoice_number: 'TransactionID',
description: 'Your payment reference number is :' + 'TransactionID',
reference_id: 'InvoiceReference'
}
],
redirect_urls: {
return_url: window.location.protocol.replace(":", "") + "://" + window.location.host.replace("/", "") + '/' + window.location.pathname.replace("/", "") + '?Success=True&RawURL=' + 'returnValue',
cancel_url: window.location.protocol.replace(":", "") + "://" + window.location.host.replace("/", "") + '/' + window.location.pathname.replace("/", "") + '?Success=False'
}
}
});
},

// onAuthorize() is called when the buyer approves the payment
onAuthorize: function (data, actions) {
var return_url = '';
// Make a call to the REST api to execute the payment
actions.payment.execute().then(function () {
//console.log(data);
return_url = data.returnUrl;
});

actions.payment.execute().then(function (res) {
if (res.state === 'approved') {

}
else {

}
}).catch(function (error) {
console.log('onCancel');
console.log(error);
});
},
// Pass a function to be called when the customer cancels the payment
onCancel: function (data, actions) {
console.log('onCancel');
console.log(data);
},
onError: function (error) {
console.log('onError');
console.log(error);
}

}, '#paypal-button-container');

<div id="paypal-button-container"></div>

Error -

![Edge_Paypal_Issue](https://user-images.githubusercontent.com/49938204/56784316-721ede80-680d-11e9-8f87-ca885c49fb5b.png)

**Comment by sandymca94** [comment]
@mcntsh and @bluepnume please help me on this issue.

**Comment by bluepnume** [comment]
Given that this is an intranet/trusted issue, there's nothing we can do but:

a) Recommend the following guides: https://developer.paypal.com/docs/checkout/troubleshoot/internet-explorer/ and https://medium.com/@bluepnume/ie-intranet-and-trusted-modes-a852d3a0bd47

b) Assure you that this should not happen for live users on your site. We have only ever seen this issue happen for users testing on their own sites, on a corporate laptop. If you can reproduce the same issue on your personal laptop or pc, please let me know.
