### ISSUE TITLE
actions.enable() not working in angular app after actions.disable()

### ISSUE THREAD

**Issue by devo253** [paypal/paypal-checkout-components#1090]
### Description

I'm trying to validate an e-mail address and eventually some other fields prior to allowing the paypal flow to begin.   I have found examples on paypal site and other github issues, and can make this work in a simple html page by calling actions.disable() and actions.enable().

However in my angular app I am hitting an issue I can't get past.    It seems that once actions.disabled() is called a second time,  then actions.enable() will no longer enable the buttons.   I have a repro project and steps below.

### Steps to reproduce

**Setup**

1.  git clone https://github.com/devo253/actionsrepro.git
2.  npm install
3.  ng serve

**Repro**

1.  Type an invalid e-mail in the text box  and attempt to click paypal buttons
2.  Paypal buttons are blocked which is good
3.  Now enter a valid e-mail address, buttons are still blocked

**More Info**

I've added console output and shows that enable is being called in the event handler. Furthermore, after first page load, if the first thing you type is a valid e-mail address, then the paypal buttons are enabled and all works.  It is only after they are disabled in the change event handler.   Is there something needed to reset them? Are there alternatives to make this work in angular?

**Comment by jfhs** [comment]
I am hitting similar issue with form validation based off [documentation](https://github.com/paypal/paypal-checkout-components/issues) on version 5.0.29 (a side question: last release in this repo is 5.0.25, where is this newer version coming from?)

After returning `actions.reject()` from `onClick` handler, button becomes non-responsive.

I've taken a look in code and the issue seems to be coming from this commit: https://github.com/paypal/paypal-smart-payment-buttons/commit/9c2510b07a52a5048e3383504da6dade3ccb673b#diff-39f43a348016e3a62dc9c315917c402b
Previously `buttonProcessing` variable which, when set to true basically disables button, was reset to `false` in [`finally` for validation promise](https://github.com/paypal/paypal-smart-payment-buttons/blob/d3329b62433b5ec47796557de094b191dcd17520/src/button.js#L165)
With commit above, its only called if [`validationPromise` returns true](https://github.com/paypal/paypal-smart-payment-buttons/blob/a782fa16e919f2597c518ae66a10dff033c12ede/src/button/button.js#L124) in `start()` promise chain [`finally`](https://github.com/paypal/paypal-smart-payment-buttons/blob/a782fa16e919f2597c518ae66a10dff033c12ede/src/button/button.js#L144).

I believe original poster issue was introduced in this commit: https://github.com/paypal/paypal-smart-payment-buttons/commit/d3329b62433b5ec47796557de094b191dcd17520
Root cause is similar: `buttonProcessing` is not reset to `false` in the part where [`buttonEnabled` condition is being checked](https://github.com/paypal/paypal-smart-payment-buttons/blob/d3329b62433b5ec47796557de094b191dcd17520/src/button.js#L68).

**Repro**
A very simple repro is to put following script to default example at [demo page](
https://developer.paypal.com/demo/checkout/#/pattern/client):
```js
        var rejected = false;
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '0.01'
                        }
                    }]
                });
            },
            onClick: function(data, actions) {
                if (!rejected) {
                    rejected = true;
                    return actions.reject();
                }
                return actions.resolve();
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                });
            }


        }).render('#paypal-button-container');
```
This code makes first click to reject validation and second to resolve. Expected behavior is to proceed with payment, however nothing happens instead.

@bluepnume Can you please take a look as it looks like you are the author of both commits? Thank you.

**Comment by bluepnume** [comment]
Thanks so much to you both for the detailed reports.

I've added some fixes and added test cases to cover both of these scenarios in https://github.com/paypal/paypal-smart-payment-buttons/commit/285227ee403b02a7167a93ac4407a11dc77732d5

Can you check and let me know if you still see any issues around this?

**Comment by bluepnume** [comment]
> (a side question: last release in this repo is 5.0.25, where is this newer version coming from?)

This is just one module in the sdk. The actual publish/release happens via https://github.com/paypal/paypal-sdk-release

**Comment by jfhs** [comment]
Your change fixed it for my case (and it looks like it should work for all of them). Thanks for such a quick fix 👍

**Comment by devo253** [comment]
Yes.  Working great in my case as well, thanks much to both!

**Comment by bluepnume** [comment]
Great, thanks for verifying!
