### ISSUE TITLE
Where is the reference documentation

### ISSUE THREAD

**Issue by richardscarrott** [paypal/paypal-checkout-components#1222]
### Description

I can't find any reference documentation for `window.paypal` anywhere?!

Obviously this link is in the README https://developer.paypal.com/docs/checkout/ however it's not really documentation. It's just a quick start + guides. Even the ["reference"](https://developer.paypal.com/docs/checkout/reference/) section isn't reference documentation (with the exception for [customizing the sdk](https://developer.paypal.com/docs/checkout/reference/customize-sdk/)).

Surely there must be detailed reference documentation for the API exposed on `window.paypal` somewhere? I currently find myself discovering new APIs by digging through the source code and GitHub issues in this repo.

It appears to be the same story for the [Checkout NodeJS SDK](https://github.com/paypal/Checkout-NodeJS-SDK).

### Steps to reproduce

1) Go to [README](https://github.com/paypal/paypal-checkout-components#paypal-checkout)
2) Try to find docs

Expect: Docs
Actual: No docs

### Affected browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge
- [x] IE
- [x] Chrome Mobile/Tablet
- [x] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [x] Other

**Comment by ahkelly** [comment]
Not sure if you are new or not to using paypal api's/sdk? but they seem to have a policy going back as long as I can remember (more then a decade) to have the worst / most confusing / disorganized (broken / obsolete links) documentation of any tech company their size that I am aware of. It is very frustrating as they clearly seem to try but their whole platform is so discombobulated I pity the documentation department's overwhelming task.

I agree, at best you get a quickstart and then "figure it out yourself from here" with links that lead nowehere and unanswered questions, etc. Problem is there system is also historically riddled with bugs so you have to know more about how to handle errors because they are going to frequently happen and I suspect most developers create their own docs based on trial and error.

**Comment by richardscarrott** [comment]
@ahkelly Yeah I'm new to PayPal and frankly I'm shocked at the state of their APIs + docs -- I integrated with Stripe recently which in comparison is an absolute dream, solid documentation and really well thought out APIs.

Of course, there's always a reason things are the way they are so I don't want to knock anybody working hard on PayPal APIs as I'm sure they're fully aware of the problem. Would be great to see some improvements though.

**Comment by wouldntsavezion** [comment]
2020/02/06, a new challenger gets in the ring, fists up, ready to code his PayPal checkout with a good jab, but he would soon learn that PayPal-land is hostile and that all that he previously learned will not help him there. He would have to learn everything without a proper doc.

No, but for real this is a rollercoaster.

**Comment by bluepnume** [comment]
@vishakha94 can you take the lead on this one? Ideally the developer.paypal.com docs should have a full reference of everything available on `window.paypal`. Thanks.

**Comment by mnicpt** [comment]
@richardscarrott Our most sincere apologies.  We are hoping to make this documentation available to you soon.  We are also open to feedback and suggestions regarding our current documentation.  I will be sure to let you know when it is live.  We are working hard and taking a look at how we can make our documentation a delight to navigate and use.

**Comment by mnicpt** [comment]
JavaScript SDK docs are in review now and will be released after this work cycle.  You will find them linked to the mentions of the JavaScript SDK.
