### ISSUE TITLE
Every version makes PayPal worse and limits functionality.

### ISSUE THREAD

**Issue by dan003400** [paypal/paypal-checkout-components#1286]
You can no longer start the payflow programmatically. This is a trivial action that can be seen all over the web on sites using old "deprecated" SDKs. (Even on the largest E commerce platform Shopify can programmatically start the payflow process)

<img width="600" alt="image" src="https://user-images.githubusercontent.com/1211542/76031199-de25a500-5efc-11ea-9de7-63cc4588c98c.png">

Reference transactions are missing, every other gateway can create additional transactions with the use of a customer tokens. Now this is no longer possible with PayPal.

The friction to use PayPal as a customer is becoming higher than manually entering credit cards.

When will the updates stop so the SDK so that developer experience isn't terrible and there isn't more friction added to the checkout process?

**Comment by fabiosussetto** [comment]
Wow, yeah this is very limiting. I hope PayPal provides an official response on this.

**Comment by bluepnume** [comment]
Hi all. If there's a specific issue I can help solve, please let me know.

In terms of relying on our button to start the checkout process, rather than starting it programmatically, this allows us to:

- Present the perfect buttons for a given buyer
- Allow the buyer to see an experience that's personalized for them
- Allow the buyer to do a seamless one-click payment in future.

Happy to help work through any specific issues that you're seeing. Generally speaking this issue board is for support with the sdk, between engineers -- rather than policy decisions that are made with regard to how PayPal works. Thanks for your feedback though.
