### ISSUE TITLE
UCC with MSP throwing error when one of merchant id passed is not eligible for UCC

### ISSUE THREAD

**Issue by Arvind6353** [paypal/paypal-checkout-components#1410]
CLient ID - AVajOV0VnH8tD0mWYqeWH22uB-DOIWPO5yRzmrqTCOeWx0oopJfeZl6NiL1NAITC3mKiTY1XuAT_mXeh

Merchant IDs - 3M5SFHD87UCNA,**FWMV7URQXNHFJ**

Here  merchant ID - FWMV7URQXNHFJ is not eligible for UCC

We are getting paypal.HostedFields.isEligible() to be true 

But when rendering Hosted fields button , it is throwing 

![image](https://user-images.githubusercontent.com/23059431/90370797-97330280-e08b-11ea-88e6-ad08b54a364d.png)

Ideally paypal.HostedFields.isEligible() should be returning false even if one of the merchantId passed does not qualify for UCC.

**Comment by weihou** [comment]
This is by design. in MSP, Paypal.HostedFields.isEligible() returns `true` when the sdk is loaded. But it returns `false` after the 2nd rendering which happens after the page is loaded.
 
The right way to integration is to add `.catch()` on `paypal.HostedFields.render()` to catch error and then hide the hosted fields.

**Comment by Arvind6353** [comment]
Thanks @weihou for the suggestion
