### ISSUE TITLE
'Dabit or Credit card' button opens a form without new window sometimes. 

### ISSUE THREAD

**Issue by uttam-iu** [paypal/paypal-checkout-components#1467]
hi,
after clicking paypal button it always opens in new window, but after clicking dabit or credit card button, sometimes it opens the form in new paypal window, sometimes it hide the paypal button and opens the form below the dabit or credit card button without new window like paypal button click. anyone please help, how to opens both in paypal new window always..

**Comment by mnicpt** [comment]
@uttam-iu It is intentional that clicking the PayPal button opens in a new window and the debit or credit card button will open a form below if standard card fields are available or guest checkout popup if they are not. https://developer.paypal.com/docs/checkout/integration-features/standard-card-fields/?mark=guest%20checkout#what-is-the-checkout-experience-if-standard-card-fields-isnt-available. So it will be conditional on whether or not standard card fields are available.

**Comment by rucebee** [comment]
https://developer.paypal.com/docs/checkout/reference/customize-sdk/#vault
vault=true enforced my setup to open in new window

**Comment by smileBeda** [comment]
I find it pretty rib-tickling that PayPal - if `vault=true` is NOT passed, simply _expands_ the credit card instead of _opening a pop up_.
Yet, it open the pop up very well for its own PayPal button, even if no vault is passed.

It literally makes no sense, and is a total Design-killer, to have different behaviour for the buttons, depending on a setting like `vault=true`.

If it is intentional, it is bad design. The expanding form is _extremely disruptive_. However, usually "unexpected behaviour" rather points to a bug.

> If the Debit or Credit Card drop-down form isn't available when your buyers check out, they are presented with the PayPal guest checkout experience in a pop-up window

What does that even mean? Why and when would the drop down not be available?
**Well, for once, clearly when you pass `vault=true`**
Can someone at PayPal explain why that might be the case?

Note that the vault is intended for _subscriptions_, and it will throw you a warning in the console if you use it on a button that is intended for capture...

I would appreciate if this actually could be corrected. It is not the correct behaviour, me thinks.

**Comment by cheeseytoastie** [comment]
It does this if you have the developer tools running in the browser. 

Took me a while to work out this was causing this behaviour.
