### ISSUE TITLE
[Feature] Add support for Svelte

### ISSUE THREAD

**Issue by Warix3** [paypal/paypal-checkout-components#1528]
### 🚀 Feature Proposal

Please add support for the Svelte framework https://svelte.dev/

### Motivation

Svelte is becoming increasingly more popular and many people use it. Currently there is no good solution to implement the smart  checkout buttons into a Svelte SPA. It needs the support like you have for react, vue and angular.

### Example

Probably something similar like the other implementations for SPA's. The only difference is that svelte is a compile time framework so it might need a sligthly different implementation than the current ones

**Comment by amyegan** [comment]
Hi @Warix3! Adding support for Svelte seems like a good idea. It will take a little while to get it added since Svelte is a compile time framework, as you mentioned, so it works a little differently from things like React that we already support. 

The good news is there is another pretty nice way to add PayPal Smart Payment Buttons to a Svelte app using [paypal-js](https://github.com/paypal/paypal-js) until we add official driver support. You can see an example of this in this [PayPal integration example with Svelte](https://github.com/paypal-examples/svelte-integration)

**Comment by Warix3** [comment]
@amyegan Thanks for the info, I was actually looking for something like paypal-js but couldn't find so I used some hacky solution before, this is much better.

**Comment by talaviram** [comment]
With the above example being used I was able to use it once it was the main component but not if I put it inside another component. i've ended up seeing this:
https://github.com/Luehang/react-paypal-button-v2/issues/30
