### ISSUE TITLE
[Bug] Empty error message returned on 3D Secure

### ISSUE THREAD

**Issue by RicLeP** [paypal/paypal-checkout-components#2084]
### 🐞 Describe the Bug
When paying with Debit / Credit Card the bank verification modal appears for a second showing the loading spinner, then closes. An empty error is then shown at the top of the payment form.

<img width="226" alt="image004" src="https://user-images.githubusercontent.com/19726976/217517992-b44b94dd-60d0-4096-b091-2ab5b2f9e158.png">

Behaviour is inconsistent between users.

### 🔬 Minimal Reproduction
Attempt payment using Debit / Credit Card

### 😕 Actual Behavior
When paying with Debit / Credit Card the bank verification modal appears for a second showing the loading spinner, then closes. An empty error is then shown at the top of the payment form.

### 🤔 Expected Behavior
Bank verification / 3D Secure window is shown (I presume this is what is meant to be shown). 

### 🌍 Environment

- Browser version: Safari - not been able to replicate on other browsers.
- OS version: iOS and Mac OS
- SDK version (`window.paypal.version`): - "5.0.350" (https://github.com/paypal/paypal-sdk-release/releases/tag/v5.0.350)

### Affected browsers
What browser(s) are affected?

- Safari
- Safari Mobile/Tablet

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.

**Comment by gyroscopes** [comment]
I can confirm this exact error (blank error message has been happening on our website). Multiple customers, different machines and OSs. I can confirm it happens on Chrome browsers too.

I also verified there are no issues with the cards, address/card information is cut and pasted. The card can be processed with a paypal virtual terminal.

After 2 weeks of complaining to paypal I've been unable to get paypal to acknowledge the issue. Currently they are saying that can reject cards for various reasons.

**Comment by craighardcastle** [comment]
I'm seeing this issue too this issue too on different devices / browsers. 3DS popup closes and a blank error message is shown on the card form

**Comment by gyroscopes** [comment]
I now have 27 messages between myself and paypal developer support since 24th Jan. This excludes phone calls and emails to the standard paypal support. Two weeks ago I was told "raised request to the product team to investigate this issue further". I've since stopped taking paypal on one of our websites.

**Comment by gyroscopes** [comment]
After reporting this in January, Paypal support have just said (21st of April 2023) that this has now been fixed. Although I should point out there was over 6 weeks of repeated denials about the problem. I stopped using paypal on the website due to the long wait. Has anyone seen this problem recently?
