### ISSUE TITLE
How to disable paypal one-touch in public kiosk PC

### ISSUE THREAD

**Issue by joweste** [paypal/paypal-checkout-components#595]
Hi, I am developing a kiosk web app.
This  kiosk app will be, off course, in a public PC.
The customers can to buy items in the kiosk and will can pay using paypal.
I am using paypal express checkout with a button.
As I am using a public PC, I´d like to disable one-touch settings for security needs,  because many customers can use the Kiosk.

How could I solve it?

I am using angularjs in my front end from paypal development docs in: https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/client-side-REST-integration/

![paypal1](https://user-images.githubusercontent.com/30800736/36066071-ce0ed494-0e8a-11e8-8773-446186f37501.png)

**Comment by bluepnume** [comment]
@walmik is this an option provided by login?

**Comment by walmik** [comment]
Yes @bluepnume the option is provided by login but it is controlled by xo. I ll check if there s some way around this and update this thread tomorrow.

**Comment by joweste** [comment]
Thank you. I will expect it

**Comment by joweste** [comment]
Only as additional info, I have noted after a user make login in the kiosk mode and get out.  The next user can use the login of the old user to make acquisitions. In kiosk mode, we can´t allow it, off course.
Is there a way to logout after the customer make your acquisitions?

**Comment by walmik** [comment]
Hello @joweste One Touch cannot be bypassed, however we are working with our product owners to find a resolution for this issue. As for your second question regarding signing out, user has to explicitly sign out (or clear cookies)

I d imagine it s not possible but I ll throw it out anyway, is there some control that you have in your Kiosk app such that it opens up Chrome in a incognito mode always so that the cookies dropped dont persist? If you indeed can, then every time the browser is closed, the cookies will be gone and the next one will be a fresh request again.

**Comment by joweste** [comment]
Hello @walmik , I disi a test and run chrome in incognito and kiosk mode as:
`"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --kiosk http://localhost --kiosk-printing  --incognito `

With this settings, after a customer login into paypal checkout at first time and finish your aquistions, it stays logged in paypal forever. The next customer using the KIOSK can to buy items using the account of the previous customer. 
This is a Kiosk app and the navigator can´t be  closed and reopen to next customer.  There will be no worker to do it.
When a customer finish you acquisitions with paypal, the start page of goods is reload and wait the next customer. 
The problem is the new customer will can buy items using the previous custommer account.

**Comment by joweste** [comment]
I think a logout option is a real need in many cases. This would bring more security to customers and the paypal.

**Comment by walmik** [comment]
You re right, incognito mode (even if it had worked) certainly cant be a solve. However as I mentioned we are working with our product owners to find a resolution for this issue - which is more like a feature I would say.

**Comment by Props0** [comment]
it pass some time, but this feature is not yet implemented ? i have the same problem using a web kiosk

**Comment by bluepnume** [comment]
@walmik have there been any developments on this one?

**Comment by walmik** [comment]
HI @Props0 and @joweste I discussed with @bluepnume and we did identify some options for the way forward. I ll let @bluepnume communicate on the ETA but by the looks of it, we ll have a solution that addresses all the concerns outlined here in this issue.

**Comment by sankaran45** [comment]
any updates on this ? we need some kind of invalidate session on checkout.js, that will internally cause the cookies that are put from paypal to be deleted -otherwise, even when we switch users, the new user gets to see the full paypal information of the prior user ... which is really bad and makes the checkout.js library completely unusable. 

if i misunderstood anything, apologies in advance, please do let me know the correct way to use the APIs
