### ISSUE TITLE
replacement for Instant Update API?

### ISSUE THREAD

**Issue by tullera** [paypal/paypal-checkout-components#599]
We have a traditional shopping cart and ship physical goods worldwide and have recently moved to using the In Context Express Checkout option along with the new (for us) paypal.Button.render API, it looks great.

However, we'd like to be able to have the customer choose shipping options based on their shipping address, and it looks like the [Instant Update API](https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECInstantUpdateAPI/) isn't available anymore. What's the recommended way to handle this? We don't want to ask for the customer's address before having them hit the PayPal button.

**Comment by bluepnume** [comment]
We're working on a new callback feature to allow for exactly what you're describing. Should be available in the next few months -- please watch this space.

**Comment by dottodot** [comment]
I asked for this feature over a year ago and it's still not available so wouldn't hold your breath.

**Comment by dottodot** [comment]
Instant API was deprecated Jan 2017

https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECInstantUpdateAPI/

and there's still no replacement

**Comment by adamduke** [comment]
Can I also add a +1 for this feature.  It's surprising that Paypal left this out when it is essential for anyone selling physical merchandise.

It causes a lot of issues and cognitive dissonance for the user.  They way the Apple Pay API does this is really smart: you get a shipingcontactselected event which can asynchonously get new shipping details and then return an object back to a shippingupdate method to update the UI.  Simples!

**Comment by nmhnmh** [comment]
Any update for this topic? The REST API supports update when execute the payment, but the checkout.js actions.payment.execute() seems missing this update feature. No way to update the payment after it's created, really need this!

**Comment by tullera** [comment]
I see some commits related to the callback feature, but can't tell if it's released and/or documented anywhere. Any hints on where you're at with this? Would be great to have this for the holidays.

**Comment by bluepnume** [comment]
Here it is! https://developer.paypal.com/docs/checkout/integration-features/shipping-callback/

**Comment by adamduke** [comment]
Apologies for the late feedback.
Regarding the onShippingChange callback: this doesn't seem to allow for the paypal UI to update with new shipping methods and rates according to the newly selected shipping address/country.

For example, if I start the payment process and then change my shipping country to a country that has different shipping methods and rates (e.g. only DHL, and NOT the previously selected method), then what should ideally happen is that the Paypal UI would update its shipping methods as a result of a callback response.  This is similar to how Apple Pay / Payment Request API works.  If we can't update the shipping methods/rates then we are still stuck: the customer has to click back to a 'confirm your order' page where they then need to select a new method and shipping rate.  It's two steps rather than one, which is cumbersome.

If you take a look here at Apple's approach you will get the general idea.  This was previously possibly in paypal with the old Instant Update API.  Of course, there are way better client-side callback ways of doing this now. :)

https://developer.apple.com/documentation/apple_pay_on_the_web/applepaysession/1778008-completeshippingcontactselection

https://developer.apple.com/documentation/apple_pay_on_the_web/applepaysession/1778009-onshippingcontactselected
