### ISSUE TITLE
Checkout button does not appear in iOS WeChat browser

### ISSUE THREAD

**Issue by jinixx** [paypal/paypal-checkout-components#706]
### Description

- Only affects WeChat iOS
- Does not work on neither sandbox nor production [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)
- Issue is consistent

As this is a huge impact on iOS payment experience, the WeChat app project I'm currently working on may not be able to provide PayPal as an alternative payment solution.

### Steps to reproduce

Load above page inside iOS WeChat browser, button does not appear

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [x] Other

**Comment by Jeffen** [comment]
It seems built-in browser of Wechat IOS does not load iframe at all. But in Wechat Web Dev Tools, everything looks fine. It makes things really hard to debug.
Also, Paypal popup window is not working in Wechat because of Wechat only support one page being displayed at each time. 

One possible solution would be use redirect only in Wechat IOS and popup window in other browsers. But I still cannot solve the iframe loading problem.

**Comment by bluepnume** [comment]
Closing this as no current plans to support wechat browser.
