### ISSUE TITLE
Billing Agreements Token with paypal button

### ISSUE THREAD

**Issue by lenlaurito** [paypal/paypal-checkout-components#985]
From this issue: https://github.com/paypal/paypal-checkout/issues/133 it says that we can use the billing agreement token with the paypal button using `resolve(billingAgreementToken)` (sample of billing agreement token would be "BA-8A802366G0648845Y") instead of `resolve(paymentId)` (as per example in [advanced integration](https://github.com/paypal/paypal-checkout/blob/master/docs/button.md#advanced-integration))

Tried the solution and it works fine. But, I haven't really been able to find this solution anywhere else in the documentation. So just wanted to ask if this is safe to use?

**Comment by mcntsh** [comment]
Hey @lenlaurito, _officially_ we recommend you integrate through Braintree Vaulting for recurring payments. See [this issue](https://github.com/paypal/paypal-checkout/issues/963) for further details.

**Comment by raRaRa** [comment]
> Hey @lenlaurito, _officially_ we recommend you integrate through Braintree Vaulting for recurring payments. See [this issue](https://github.com/paypal/paypal-checkout/issues/963) for further details.

Any particular reason behind this? We just had to drop support for Braintree for our business, for many reasons. A few examples:

1. They only offer settlement in EUR for Iceland. This means that if our customer pays us $10, it needs to be exchanged to EUR and then to ISK. We're losing a lot of money because of this.
2. They send each transaction immediately within 1-3 business days to your bank. Our bank is charging us 5 USD per transaction (other banks in Iceland charge more). So if 10 people pay us today, we need to pay 50 USD in transaction fee. Ridiculous.

I'd much rather use PayPal since I can send all payments as one transaction to our bank. Do I need to worry about PayPal deprecating recurring payments?
